language: php

sudo: false

cache:
  directories:
        - $HOME/.composer/cache

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
 - travis_retry composer install --no-ansi --dev --no-interaction --no-progress --no-scripts --optimize-autoloader

script:
  - ant travis
